version: '3.8'

services:
  smallqr:
    build: .
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      - FLASK_ENV=production
      - PORT=8002
      - BASE_PATH=/smallqr
      - SECURE_COOKIES=true
    restart: unless-stopped
    working_dir: /app
