version: '3.8'

services:
  smallqr:
    build: .
    ports:
      - "8002:8002"          # Expose container port to host
    environment:
      - FLASK_ENV=production
      - PORT=8002
      - BASE_PATH=/smallqr
      - SCRIPT_NAME=/smallqr
    restart: unless-stopped
    working_dir: /app
