version: '3.8'
services:
  smallqr:
    build: .
    ports:
      - "8002:8002"
    environment:
      - FLASK_ENV=production
      - PORT=8002
    restart: unless-stopped
    working_dir: /app
    command: flask run --host=127.0.0.1 --port=8002
