version: '3.8'
services:
  smallqr:
    build: .
    ports:
      - "8002:8002"
    environment:
      - FLASK_ENV=production
      - PORT=8002
      - BASE_PATH=/smallqr
      - SCRIPT_NAME=/smallqr
    restart: unless-stopped
    working_dir: /app
    # Option 1: Dev server (not recommended for prod)
    # command: flask run --host=0.0.0.0 --port=8002

    # Option 2: Gunicorn (recommended)
    # Caddy (systemd) should reverse proxy /smallqr to this container
    command: gunicorn -w 4 -b 0.0.0.0:8002 app:app
