name: CI - Test SmallQR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzbar0 zbar-tools curl

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r webapp/requirements.txt
          pip install coverage coveralls

      - name: Start Flask app (background)
        working-directory: webapp
        run: |
          nohup gunicorn -w 4 -b 0.0.0.0:8002 app:app &
          sleep 5

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s webapp -p 'test_app.py'
          coverage report
          coverage xml
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml
